#pragma once

#include "Core.h"
#include "Application.h"
#include "EntryPoint.h"

//sge
#include "Context.h"
#include "Window.h"
#include "Model.h"
#include "Object3D.h"
#include "Shader.h"
#include "Transform.h"
#include "Material.h"
#include "Texture.h"
#include "Light.h"
#include "DirectionalLight.h"
#include "PointLight.h"
#include "ICamera.h"
#include "FlyCamera.h"
#include "EditorCamera.h"
#include "Scene.h"
#include "Skybox.h"
#include "PostProcess.h"
#include "Input.h"
#include "Keyboard.h"
#include "Mouse.h"
#include "EventSystem.h"
#include "Quad.h"
#include "Box.h"
#include "Sphere.h"
